// Code generated by Icestudio 0.3.1
// Mon, 19 Feb 2018 20:41:26 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // Input/Output
 reg 0;
 reg 1;
 wire vga_h_sync;
 wire vga_v_sync;
 wire CounterX;
 wire CounterY;
 
 // Module instance
 main MAIN (
  .v602c81(0),
  .v0a7437(1),
  .vda6c06(vga_h_sync),
  .ve6a833(vga_v_sync),
  .vcb60db(CounterX),
  .v3ffdd4(CounterY)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  0 = 0;
  1 = 0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
