// Code generated by Icestudio 0.5.1n210107

`default_nettype none

//---- Top entity
module main (
 input v1c67bd,
 input vc02291,
 output v9ad371
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v1c67bd;
 assign w1 = vc02291;
 assign v9ad371 = w2;
 main_v7d3e91 v7d3e91 (
  .d_in(w0),
  .d_out_en(w1),
  .d_out_z(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- tristate_o  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- trisate 
/*-------------------------------------------------*/

module main_v7d3e91 (
 input d_in,
 input d_out_en,
 output d_out_z
);
 
 assign d_out_z = d_out_en ? d_in : 1'bz;
endmodule
